.TH LSFRAMEWORK 1 "Mac-Utils Repository Docs"
.SH NAME
lsframework - list frameworks in a directory
.SH SYNOPSIS
.B lsframework
[\fIOPTIONS\fR] [\fIARGUMENT\fR]
.SH DESCRIPTION
The \fBlsframework\fR utility recursively descends the directory tree searching for .framework directories and returns their full paths as a JSON array
.SH OPTIONS
.TP
.BR \-p ", " \-\-path
Search the directory at the path specified for frameworks
.TP
.BR \-i ", " \-\-interactive
Ask for the path to the directory to search for frameworks with an interactive prompt
.TP
.BR \-h ", " \-\-help
Show this help message
.SH PROJECT
.PP
This script is from the \fBmac-utils\fR repo on GitHub.
.PP
\fBmac-utils\fR is a collection of useful (mostly macOS specific) shell scripts.

\fBGitHub:\fR \fIhttps://github.com/Soliez/mac-utils\fR