.TH URLENCODE 1 "Mac-Utils Repository Docs"
.SH NAME
urlencode - Percent Encoding Utility
.SH SYNOPSIS
.B urlencode
[\fIOPTION\fR] [\fIARGUMENT\fR]
.SH DESCRIPTION
The \fBurlencode\fR utility is used to perform percent-encoding operations on data
.SH OPTIONS
.TP
.BR \-e ", " \-\-encode
Percent-encode the input data
.TP
.BR \-d ", " \-\-decode
Percent-decode the input data
.TP
.BR \-h ", " \-\-help
Show this help message
.SH PROJECT
.PP
This script is from the \fBmac-utils\fR repo on GitHub.
.PP
\fBmac-utils\fR is a collection of useful (mostly macOS specific) shell scripts.

\fBGitHub:\fR \fIhttps://github.com/Soliez/mac-utils\fR