.TH URLNAME 1 "Mac-Utils Repository Docs"
.SH NAME
urlname - Retrieve the title of a webpage
.SH SYNOPSIS
.B urlname
[\fIOPTION\fR] [\fIARGUMENT\fR]
.SH DESCRIPTION
The \fBurlname\fR utility is used to retrieve the title of a webpage by parsing its title tag
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show this help message
.SH EXAMPLES
.nf
urlname "https://github.com/Soliez/mac-utils"
.fi
.SH PROJECT
.PP
This script is from the \fBmac-utils\fR repo on GitHub.
.PP
\fBmac-utils\fR is a collection of useful (mostly macOS specific) shell scripts.

\fBGitHub:\fR \fIhttps://github.com/Soliez/mac-utils\fR